# Для Полины и Алены
import psycopg2

class Database:
    def __init__(self):
        db = psycopg2.connect(dbname='database', user='db_user', password='mypassword', host='localhost')
        self.cur = db.cursor()
        self.cur.execute(""" CREATE TABLE "ПРЕДСТАВИТЕЛЬ IT"
                            (
                            "ID" character CHECK( LENGTH("ID") >=5 AND  LENGTH("ID") <=32),
                            "CHAT ID" character varying (64),
                            "ФАМИЛИЯ" character varying (64),
                            "ИМЯ" character varying (64),
                            "ЗАДАЧА" integer,
                            PRIMARY KEY ("ID")
                            ); """)

        self.cur.execute(""" CREATE TABLE "ПРЕДСТАВИТЕЛЬ НКО"
                             (
                             "ID" character CHECK( LENGTH("ID") >=5 AND  LENGTH("ID") <=32),
                             "CHAT ID" character varying (64),
                             "ФАМИЛИЯ" character varying (64),
                             "ИМЯ" character varying (64),
                             PRIMARY KEY ("ID")
                             ); """)

        self.cur.execute(""" CREATE TABLE "МОДЕРАТОР"
                            (
                            "ID" character CHECK( LENGTH("ID") >=5 AND  LENGTH("ID") <=32),
                            “CHAT ID” character varying (64),
                            "ФАМИЛИЯ" character varying (64),
                            "ИМЯ" character varying (64),
                            PRIMARY KEY ("ID")
                            ); """)

        self.cur.execute(""" CREATE TABLE "ЗАДАЧА"
                            (
                            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                            "ЗАКАЗЧИК" character CHECK( LENGTH("ID") >=5 AND  LENGTH("ID") <=32),
                            "СФЕРА" integer,
                            "ИСПОЛНИТЕЛЬ" character CHECK( LENGTH("ID") >=5 AND  LENGTH("ID") <=32),
                            "ОПИСАНИЕ" character varying (500),
                            "СОСТОЯНИЕ" integer,
                            PRIMARY KEY ("ID")
                            ); """)

        self.cur.execute(""" CREATE TABLE "СФЕРА"
                            (
                            "ID" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                            "НАЗВАНИЕ" character varying (50),
                            PRIMARY KEY ("ID")
                            ); """)

        self.cur.execute(""" CREATE TABLE "СФЕРА - IT"
                            (
                            "СФЕРА" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
                            "ПРЕДСТАВИТЕЛЬ IT" character CHECK( LENGTH("ID") >=5 AND  LENGTH("ID") <=32),
                            
                            PRIMARY KEY ("ID")
                            );""")

        # self.users = []

    def create_it_person(self, id, surname, name):
        self.cur.execute(""" INSERT INTO “ПРЕДСТАВИТЕЛЬ IT” VALUES (id, surname, name, 0); """)

    def create_nko_person(self, ):
        self.cur.execute(""" INSERT INTO “ПРЕДСТАВИТЕЛЬ НКО” VALUES (id, surname, name); """)

    def create_moderator(self, ):
        self.cur.execute(""" INSERT INTO “МОДЕРАТОР” VALUES (id, surname, name); """)

    def get_spheres(self):
        """ выдает список сфер обязательно всегда в одном и том же порядке (сортируйте по id)"""
        # return ["Дизайн", "Создатель сайтов", "Аналитик", "Дата сайнтист"]
        return self.cur.execute(""" SELECT "НАЗВАНИЕ" FROM "СФЕРА"; """)

    def get_user_spheres(self, username):
        """"""
        return self.cur.execute(""" SELECT * FROM "СФЕРА - IT" WHERE ID=username; """)

    def add_spheres2user(self, username, list_id_spheres):
        for id_sphere in list_id_spheres:
            self.cur.execute(""" INSERT INTO “СФЕРА - IT” VALUES (id_sphere, username); """)

    def add_task(self, id_nko, id_sphere, description):
        return self.cur.execute(""" INSERT INTO “ЗАДАЧА” VALUES 
                                    (SELECT COUNT(*) FROM "ЗАДАЧА", id_nko, 
                                    id_sphere, id_it = None, description, condition = 1) """)

    def get_tasks4moderator(self):
        return self.cur.execute(""" SELECT * FROM “ЗАДАЧА” WHERE “ЗАДАЧА”."СОСТОЯНИЕ" = 1 """)

    def update_condition_task(self, selected_task, condition):
        """если задачу на доработку, то передать 2, иначе 3"""
        self.cur.execute(""" UPDATE “ЗАДАЧА” SET "СОСТОЯНИЕ"=condition WHERE ID=selected_task """)

    def update_task(self, selected_task, id_sphere, description):
        self.cur.execute(""" UPDATE “ЗАДАЧА” SET "СОСТОЯНИЕ" = 1,
                             "СФЕРА" = id_sphere, "ОПИСАНИЕ" = description WHERE
                             ID = selected_task(?); """)

    def get_task4it(self):
        self.cur.execute(""" SELECT ЗАКАЗЧИК, СФЕРА.НАЗВАНИЕ, ОПИСАНИЕ FROM ЗАДАЧА, СФЕРА 
                             JOIN  "СФЕРА - IT" ON  "СФЕРА - IT"."СФЕРА" = СФЕРА.ID 
                             WHERE  СФЕРА.ID = ЗАДАЧА.СФЕРА AND  
                             "СФЕРА - IT"."ПРЕДСТАВИТЕЛЬ IT" = id_it
                             ;""")

    def select_task(self, id_it, selected_task):
        self.cur.execute(""" UPDATE “ЗАДАЧИ” SET "СОСТОЯНИЕ"=4, “ИСПОЛНИТЕЛЬ”=id_it WHERE ID=selected_task; """)

    def submit_task(self, selected_task):
        self.cur.execute(""" UPDATE “ЗАДАЧИ” SET "СОСТОЯНИЕ"=5 WHERE ID=selected_task; """)

    def get_condition4nko(self, id_nko):
        return self.cur.execute(""" SELECT ИСПОЛНИТЕЛЬ, ОПИСАНИЕ, СОСТОЯНИЕ FROM “ЗАДАЧИ” WHERE “ЗАКАЗЧИК”=id_nko; """)

    def delete_it(self, id_it):
        self.cur.execute(""" DELETE FROM "ПРЕДСТАВИТЕЛЬ IT" WHERE ID = id_it;
                             UPDATE “ЗАДАЧА” SET "СОСТОЯНИЕ"=3 
                             WHERE ИСПОЛНИТЕЛЬ = id_it;
                             DELETE FROM "СФЕРА - IT" WHERE "ПРЕДСТАВИТЕЛЬ IT" = id_it; """)

    def delete_nko(self, id_nko):
        self.cur.execute(""" DELETE FROM "ПРЕДСТАВИТЕЛЬ НКО" WHERE ID = id_nko;
                             DELETE FROM “ЗАДАЧА” WHERE "ЗАКАЗЧИК" = id_nko; """)

    def delete_moderator(self, id_moderator):
        self.cur.execute(""" DELETE FROM "МОДЕРАТОР" WHERE ID = id_moderator; """)

    def update_sphere(self):
        self.cur.execute(""" DELETE FROM "СФЕРА - IT" WHERE "ПРЕДСТАВИТЕЛЬ IT" = id_it;
                             INSERT INTO “СФЕРА - IT” VALUES 
                             (id_sphere, id_it); """)

bot_db = Database()